//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class ManagerBase_SoundManagerWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(ManagerBase<SoundManager>), typeof(System.Object), "ManagerBase_SoundManager");
		L.RegFunction("OnInit", OnInit);
		L.RegFunction("New", _CreateManagerBase_SoundManager);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("Instance", get_Instance, null);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateManagerBase_SoundManager(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				ManagerBase<SoundManager> obj = new ManagerBase<SoundManager>();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: ManagerBase<SoundManager>.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnInit(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			ManagerBase<SoundManager> obj = (ManagerBase<SoundManager>)ToLua.CheckObject<ManagerBase<SoundManager>>(L, 1);
			obj.OnInit();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Instance(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, ManagerBase<SoundManager>.Instance);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

